//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFC_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKho
    {
        public string MaKho { get; set; }
        public string MaNVL { get; set; }
        public string DVT { get; set; }
        public int SoLuongT { get; set; }
    
        public virtual Kho Kho { get; set; }
        public virtual NguyenVL NguyenVL { get; set; }
    }
}
