//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFC_Framework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KFCEntities : DbContext
    {
        public KFCEntities()
            : base("name=KFCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietNVL> ChiTietNVLs { get; set; }
        public virtual DbSet<CTDonDatHang> CTDonDatHangs { get; set; }
        public virtual DbSet<CTHoaDon> CTHoaDons { get; set; }
        public virtual DbSet<DonDatHang> DonDatHangs { get; set; }
        public virtual DbSet<GiamGia> GiamGias { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<Kho> Khoes { get; set; }
        public virtual DbSet<LoaiHang> LoaiHangs { get; set; }
        public virtual DbSet<NguyenVL> NguyenVLs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<ChiTietKho> ChiTietKhoes { get; set; }
    
        public virtual int DeleteCustomerAccount(string maTK)
        {
            var maTKParameter = maTK != null ?
                new ObjectParameter("MaTK", maTK) :
                new ObjectParameter("MaTK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCustomerAccount", maTKParameter);
        }
    
        public virtual int DeleteGiamGiaAndUpdateSanPham(string maGG)
        {
            var maGGParameter = maGG != null ?
                new ObjectParameter("MaGG", maGG) :
                new ObjectParameter("MaGG", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteGiamGiaAndUpdateSanPham", maGGParameter);
        }
    }
}
