//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFC_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenVL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguyenVL()
        {
            this.ChiTietNVLs = new HashSet<ChiTietNVL>();
            this.ChiTietKhoes = new HashSet<ChiTietKho>();
        }
    
        public string MaNVL { get; set; }
        public string TenNVL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNVL> ChiTietNVLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKho> ChiTietKhoes { get; set; }
    }
}
